CREATE TABLE `Te_BaseField` (
  `Id` int(11) NOT NULL AUTO_INCREMENT,
  `BoolField` bit(1) NOT NULL,
  `BoolFieldNull` bit(1) DEFAULT NULL,
  `SbyteField` tinyint(4) NOT NULL,
  `SbyteFieldNull` tinyint(4) DEFAULT NULL,
  `ByteField` tinyint(3) unsigned NOT NULL,
  `ByteFieldNull` tinyint(3) unsigned DEFAULT NULL,
  `Int16Field` smallint(6) NOT NULL,
  `Int16FieldNull` smallint(6) DEFAULT NULL,
  `UInt16Field` smallint(5) unsigned NOT NULL,
  `UInt16FieldNull` smallint(6) unsigned DEFAULT NULL,
  `Int32Field` int(11) NOT NULL,
  `Int32FieldNull` int(11) DEFAULT NULL,
  `UInt32Field` int(10) unsigned NOT NULL,
  `UInt32FieldNull` int(10) unsigned DEFAULT NULL,
  `Int64Field` bigint(20) NOT NULL,
  `Int64FieldNull` bigint(20) DEFAULT NULL,
  `UInt64Field` bigint(20) unsigned NOT NULL,
  `UInt64FieldNull` bigint(20) unsigned DEFAULT NULL,
  `FloatField` float NOT NULL,
  `FloatFieldNull` float DEFAULT NULL,
  `DoubleField` double NOT NULL,
  `DoubleFieldNull` double DEFAULT NULL,
  `DecimalField` decimal(10,4) NOT NULL,
  `DecimalFieldNull` decimal(10,4) DEFAULT NULL,
  `DateTimeField` datetime NOT NULL,
  `DateTimeFieldNull` datetime DEFAULT NULL,
  `VarcharField` varchar(2000) NOT NULL,
  `VarcharFieldNull` varchar(2000) DEFAULT NULL,
  `TextField` text NOT NULL,
  `TextFieldNull` text,
  `BigDataField` blob NOT NULL,
  `BigDataFieldNull` blob,
  `EnumInt32Field` int(11) NOT NULL,
  `EnumInt32FieldNull` int(11) DEFAULT NULL,
  `EnumInt64Field` bigint(20) NOT NULL,
  `EnumInt64FieldNull` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`Id`)
) ENGINE=InnoDB AUTO_INCREMENT=6001 DEFAULT CHARSET=utf8 ROW_FORMAT=COMPACT;