CREATE TABLE "public"."Te_BaseField" (
  "Id" serial,
  "BoolField" bool NOT NULL,
  "BoolFieldNull" bool,
  "SbyteField" int2 NOT NULL,
  "SbyteFieldNull" int2,
  "ByteField" int2 NOT NULL,
  "ByteFieldNull" int2,
  "Int16Field" int2 NOT NULL,
  "Int16FieldNull" int2,
  "UInt16Field" int4 NOT NULL,
  "UInt16FieldNull" int4,
  "Int32Field" int4 NOT NULL,
  "Int32FieldNull" int4,
  "UInt32Field" int8 NOT NULL,
  "UInt32FieldNull" int8,
  "Int64Field" int8 NOT NULL,
  "Int64FieldNull" int8,
  "UInt64Field" numeric(20) NOT NULL,
  "UInt64FieldNull" numeric(20),
  "FloatField" float4 NOT NULL,
  "FloatFieldNull" float4,
  "DoubleField" float8 NOT NULL,
  "DoubleFieldNull" float8,
  "DecimalField" numeric(10,4) NOT NULL,
  "DecimalFieldNull" numeric(10,4),
  "DateTimeField" timestamp(6) NOT NULL,
  "DateTimeFieldNull" timestamp(6),
  "VarcharField" varchar(2000) COLLATE "pg_catalog"."default" NOT NULL,
  "VarcharFieldNull" varchar(2000) COLLATE "pg_catalog"."default",
  "TextField" text COLLATE "pg_catalog"."default" NOT NULL,
  "TextFieldNull" text COLLATE "pg_catalog"."default",
  "BigDataField" bytea NOT NULL,
  "BigDataFieldNull" bytea,
  "EnumInt32Field" int4 NOT NULL,
  "EnumInt32FieldNull" int4,
  "EnumInt64Field" int8 NOT NULL,
  "EnumInt64FieldNull" int8,
  CONSTRAINT "Te_BaseField_pkey" PRIMARY KEY ("Id")
)
;
